# -*- coding: utf-8 -*-
"""Superstore_Sales_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fc1XitLVs_bIQj8JFkWEJMWwQ-58rHMU
"""

import pandas as pd

# Load the dataset
df = pd.read_csv('/content/Sample - Superstore.csv',encoding='latin1')

# Show the first 5 rows
df.head()

# Shape of the dataset (rows, columns)
df.shape

# Column names
df.columns

# Info about datatypes
df.info()

# Summary statistics
df.describe()

df['Order Date'] = pd.to_datetime(df['Order Date'])

df = df.drop_duplicates()

df.isnull().sum()

"""# Save as CSV
df.to_csv('/content/Cleaned_Superstore.csv', index=False)

# Save as Excel
df.to_excel('/content/Cleaned_Superstore.xlsx', index=False)

"""

df['Sales'].sum(), df['Profit'].sum()

df.groupby('Category')['Sales'].sum()

df.groupby('Product Name')['Sales'].sum().sort_values(ascending=False).head(10)

import matplotlib.pyplot as plt

monthly_sales = df.resample('M', on='Order Date')['Sales'].sum()

plt.figure(figsize=(12,6))
monthly_sales.plot()
plt.title("Monthly Sales Trend")
plt.xlabel("Month")
plt.ylabel("Sales")
plt.show()

df.groupby('Category')['Sales'].sum().sort_values(ascending=False)

df.groupby('Region')['Profit'].sum().sort_values(ascending=False)

df.groupby('Customer Name')['Sales'].sum().sort_values(ascending=False).head(10)

import matplotlib.pyplot as plt

monthly_sales = df.resample('M', on='Order Date')['Sales'].sum()

plt.figure(figsize=(12,6))
monthly_sales.plot(color='green')
plt.title("Monthly Sales Trend")
plt.xlabel("Month")
plt.ylabel("Sales")
plt.show()

df.groupby('Category')['Sales'].sum().plot(kind='bar', color=['skyblue','orange','pink'])
plt.title("Total Sales by Category")
plt.ylabel("Sales")
plt.show()

df.groupby('Region')['Profit'].sum().plot(kind='bar', color='purple')
plt.title("Profit by Region")
plt.ylabel("Profit")
plt.show()